services:
  calendar-puzzle:
    image: calendar-puzzle
    build: .
    ports:
      - "${PORT}:3001"
    environment:
      - TZ=Asia/Jerusalem
      - NODE_ENV=production
      - DATABASE_URL=postgresql://puzzle:${POSTGRES_PASSWORD}@postgres:5432/puzzle
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    volumes:
      - ./secret-key:/usr/app/secret-key:ro
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:18.1-alpine3.23
    environment:
      - POSTGRES_USER=puzzle
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=puzzle
    volumes:
      - calendar_puzzle_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  calendar_puzzle_postgres_data:
