name: Node CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '24' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Setup NodeJS
        uses: actions/setup-node@v6.1.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Dependencies Install
        run: npm ci
        env:
          CI: true

      - name: Playwright Install
        run: npx playwright install --with-deps chromium
        env:
          CI: true

      - name: Test
        run: npm run test
        env:
          CI: true

      - name: Build
        run: npm run build